import { z } from 'zod'

import { JsonValueSchema } from '../common/json.js'
import { HeliosModuleCodeSchema, HeliosModuleScopeSchema } from './modules.js'

export const AuditActorTypeSchema = z.enum(['user', 'system'])
export const AuditEntityTypeSchema = z.enum([
  'user',
  'catalog_group',
  'scheduling_run',
  'scheduling_candidate',
  'pending_purchase_apply_request',
  'pending_purchase_packet',
  'pending_purchase_row',
  'proposal_batch',
  'proposal_row',
  'proposal_line_item',
  'desired_state_revision',
  'job',
  'write_operation',
  'llm_run',
  'undo_event',
  'communications_policy_replacement_packet',
  'catalog_brand',
  'catalog_item',
  'comment',
  'annotation',
  'brand_expiry_override',
])
export const AuditEventTypeSchema = z.enum([
  'auth.user.signed_in',
  'auth.user.provisioned',
  'auth.user.role_changed',
  'auth.user.active_changed',
  'auth.user.name_changed',
  // Emitted by PATCH /api/users/:id when an admin changes a user's
  // metric_grants set. Payload carries both before + after sets.
  'auth.user.metric_grants_changed',
  'pending_purchase.packet.generation_requested',
  'pending_purchase.packet.generated',
  'pending_purchase.packet.import_requested',
  'pending_purchase.packet.imported',
  'pending_purchase.apply.requested',
  'pending_purchase.apply.completed',
  'pending_purchase.row.approval_updated',
  'pending_purchase.row.edited',
  'proposal.batch.generation_requested',
  'proposal.batch.generated',
  'proposal.batch.import_requested',
  'proposal.batch.imported',
  'proposal.line_item.edited',
  'proposal.line_item.note_updated',
  'proposal.line_item.approved',
  'proposal.line_item.rejected',
  'desired_state.paused',
  'desired_state.resumed',
  'catalog.full_sync.requested',
  'catalog.group.refresh_requested',
  'screens.banner_bulk_toggle.requested',
  'screens.banner_bulk_toggle.completed',
  'screens.banner_refresh.requested',
  'screens.banner_refresh.completed',
  'screens.banner_health_maintenance.requested',
  'screens.banner_health_maintenance.completed',
  'screens.enable_healthy_banners.requested',
  'screens.enable_healthy_banners.completed',
  'screens.bronx_midtown_image_clone.requested',
  'screens.bronx_midtown_image_clone.completed',
  'screens.midtown_priced_to_move_promo_rebind.requested',
  'screens.midtown_priced_to_move_promo_rebind.completed',
  'screens.image_banner_sync.requested',
  'screens.image_banner_sync.completed',
  'screens.banner_duplicate.requested',
  'screens.banner_duplicate.completed',
  'scheduling.run.requested',
  'scheduling.run.extracted',
  'scheduling.run.normalized_input_saved',
  'scheduling.run.candidate_generation_requested',
  'scheduling.run.run_now_requested',
  'scheduling.run.cancelled',
  'scheduling.run.candidates_generated',
  'scheduling.candidate.selected',
  'llm.run.rerun_requested',
  'undo.requested',
  'communications.policy_replacement_review.draft_saved',
  'communications.policy_replacement_review.submitted',
  'catalog.review.row.rerun_requested',
  'catalog.review.row.failed',
  'catalog.comment.created',
  'catalog.comment.deleted',
  'catalog.annotation.created',
  'catalog.annotation.retracted',
  'catalog.warehouse_location.assigned',
  'config.workers.schedule_updated',
  'config.workers.stock_refresh.requested',
  'config.workers.stock_refresh.completed',
  'config.workers.litalerts_refresh.requested',
  'config.workers.litalerts_refresh.completed',
  'config.workers.catalog_refresh.requested',
  'config.workers.catalog_refresh.completed',
  'config.workers.edible_thc_clamp.requested',
  'config.workers.edible_thc_clamp.completed',
  'config.workers.sweed_orders_raw_json_drain.requested',
  'config.workers.sweed_orders_raw_json_drain.completed',
  'config.workers.litalerts_products_raw_json_drain.requested',
  'config.workers.litalerts_products_raw_json_drain.completed',
  'config.workers.fuzzy_skus_retention.requested',
  'config.workers.fuzzy_skus_retention.completed',
  'config.workers.stock_snapshot_items_retention.requested',
  'config.workers.stock_snapshot_items_retention.completed',
  'config.workers.litalerts_retailer_backfill.requested',
  'config.workers.litalerts_retailer_backfill.completed',
  'config.workers.sweed_orders_ingest.requested',
  'config.workers.sweed_orders_ingest.completed',
  'config.workers.sweed_package_snapshots.requested',
  'config.workers.sweed_package_snapshots.completed',
  'config.workers.sweed_purchases_ingest.requested',
  'config.workers.sweed_purchases_ingest.completed',
  'config.workers.sweed_shifts_ingest.requested',
  'config.workers.sweed_shifts_ingest.completed',
  'config.workers.enrich_customer_address.requested',
  'config.workers.enrich_customer_address.completed',
  'config.workers.enrich_delivery_address.requested',
  'config.workers.enrich_delivery_address.completed',
  'config.workers.enrich_visitor_scan_address.requested',
  'config.workers.enrich_visitor_scan_address.completed',
  'config.workers.weather_daily_ingest.requested',
  'config.workers.weather_daily_ingest.completed',
  'config.workers.market_evidence_alarm.completed',
  'config.brand_expiry_override.upserted',
  'config.brand_expiry_override.deleted',
])

export type AuditEntityType = z.infer<typeof AuditEntityTypeSchema>
export type AuditEventType = z.infer<typeof AuditEventTypeSchema>

export const AuditEventRecordSchema = z.object({
  actorLabel: z.string(),
  createdAt: z.iso.datetime(),
  entityId: z.string(),
  entityType: AuditEntityTypeSchema,
  eventId: z.number().int().positive(),
  eventType: AuditEventTypeSchema,
  module: HeliosModuleCodeSchema,
  payload: JsonValueSchema,
  scope: HeliosModuleScopeSchema.nullable(),
  summaryText: z.string(),
  undoAvailable: z.boolean(),
  undo: z.object({
    status: z.enum(['queued', 'running', 'completed', 'failed']),
    undoEventId: z.number().int().positive(),
  }).nullable(),
})
export type AuditEventRecord = z.infer<typeof AuditEventRecordSchema>
