-- White-label bulk-flower pricing snapshots
--
-- Versioned, append-mostly. Every "Save" in the helios
-- Catalog→WhiteLabel→Pricing editor writes one new row containing the
-- entire reviewed snapshot — cost basis, GM choices, per-row and
-- per-brand decisions, the computed OTD prices, and the public
-- projection — as a single JSONB payload. The most recent row is
-- marked is_current=true and is the only one the public bulk-flower
-- menu reads from. The partial unique index enforces "at most one
-- current snapshot at a time".

create table if not exists whitelabel_pricing_snapshots (
  id              bigserial primary key,
  created_at      timestamptz not null default now(),
  created_by      text not null,
  -- The cost basis was generated by a Sweed scan earlier than the
  -- save click — record both timestamps so the public page can be
  -- explicit about price-data freshness without dragging in the
  -- inventory tables.
  cost_basis_generated_at timestamptz not null,
  payload_version integer not null default 1,
  payload         jsonb not null,
  is_current      boolean not null default false
);

create unique index if not exists whitelabel_pricing_snapshots_one_current
  on whitelabel_pricing_snapshots (is_current)
  where is_current = true;

create index if not exists whitelabel_pricing_snapshots_created_at
  on whitelabel_pricing_snapshots (created_at desc);
