/**
 * Apply-and-push for a tenant parser config (issue #19 L5).
 *
 * Validates a proposed JSONC blob against the parsekit contract +
 * dialect, writes it to the in-memory git mirror used by the runtime
 * loader (HELIOS_PARSER_CONFIGS_LOCAL_DIR), commits, and pushes to
 * origin/master.
 *
 * Failure modes are loud and structured — the UI surfaces them so the
 * operator can iterate without leaving the page:
 *   - 'invalid_jsonc'        : JSONC parse error.
 *   - 'schema_invalid'       : structural issue (configVersion, scope,
 *                              dialectRef, etc.).
 *   - 'identity_mismatch'    : useCase / tenantId don't match the
 *                              targeted file (typo guard).
 *   - 'dialect_unknown' / 'contract_unknown' / 'verify_failed' /
 *     'compile_failed' / 'golden_failed' : standard parsekit gates.
 *   - 'git_push_failed'      : push rejected by origin (permissions,
 *                              non-fast-forward, network).
 *   - 'mirror_unavailable'   : HELIOS_PARSER_CONFIGS_LOCAL_DIR not
 *                              configured or not initialised.
 *
 * On success the runtime registry's next periodic refresh tick picks
 * up the new release; we do NOT force a synchronous re-load to keep
 * the apply path snappy.
 */

import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import { parse as parseJsonc, type ParseError } from 'jsonc-parser'

import { compileParser } from '../../lib/parsekit/engine.js'
import { parseWith } from '../../lib/parsekit/engine.js'
import { getParserRegistry } from '../../lib/parsekit/node/parserRegistry.js'
import { verifyParser } from '../../lib/parsekit/verify.js'
import { litalertsContract, litalertsOutputFields } from '../../lib/parsekit/contracts/litalerts.js'
import { litalertsV1Dialect } from '../../lib/parsekit/dialects/litalerts-v1.js'
import type { TenantParserConfig } from '../../lib/parsekit/types.js'

const USE_CASE = 'litalerts'
const DEFAULT_DIALECT_ID = 'litalerts-v1'

const HEADER_COMMENT = [
  '// AUTOGENERATED by /config/parsing/litalerts apply-and-push.',
  '// Source: helios/src/client/routes/config/ConfigParsingLitalertsPage.tsx',
  '// Edits applied here are committed straight to master of',
  '// helios-parser-configs; the runtime loader picks them up within',
  '// HELIOS_PARSER_CONFIGS_REFRESH_SECONDS (default 60s).',
  '',
].join('\n')

export interface ApplyConfigInput {
  tenantId: string
  /** Full JSONC body of the proposed config (without the autogen comment header). */
  jsonc: string
  /** Free-form note appended to the commit message — usually the
   *  operator's intent + the LLM rationale snippet. */
  note: string
  /** "<email>" of the operator driving the apply — used for the
   *  commit's Author trailer so audits trace back. */
  actorEmail: string
}

export type ApplyConfigFailureCode =
  | 'invalid_jsonc'
  | 'schema_invalid'
  | 'identity_mismatch'
  | 'dialect_unknown'
  | 'dialect_version_mismatch'
  | 'contract_unknown'
  | 'verify_failed'
  | 'compile_failed'
  | 'golden_failed'
  | 'mirror_unavailable'
  | 'git_command_failed'
  | 'git_push_failed'

export interface ApplyConfigFailure {
  ok: false
  code: ApplyConfigFailureCode
  message: string
  detail?: unknown
}

export interface ApplyConfigSuccess {
  ok: true
  /** File path written, relative to the parser-configs repo root. */
  relPath: string
  /** Commit SHA produced by `git commit`. */
  commitSha: string
  /** Whether `git push` actually transferred anything (false ⇒
   *  push succeeded but the remote was already at our HEAD). */
  pushed: boolean
}

export type ApplyConfigResult = ApplyConfigSuccess | ApplyConfigFailure

export async function applyLitalertsTenantConfig(
  input: ApplyConfigInput,
): Promise<ApplyConfigResult> {
  const localDir = (process.env.HELIOS_PARSER_CONFIGS_LOCAL_DIR ?? '').trim()
  if (!localDir) {
    return {
      ok: false,
      code: 'mirror_unavailable',
      message: 'HELIOS_PARSER_CONFIGS_LOCAL_DIR is not set; the apply path needs a writable working tree.',
    }
  }
  const repoRoot = resolve(localDir)

  // 1. Parse JSONC.
  const parseErrors: ParseError[] = []
  const config = parseJsonc(input.jsonc, parseErrors, {
    disallowComments: false,
    allowTrailingComma: false,
  }) as unknown as TenantParserConfig | undefined
  if (parseErrors.length > 0 || !config) {
    return {
      ok: false,
      code: 'invalid_jsonc',
      message: `${parseErrors.length} JSONC parse error(s)`,
      detail: parseErrors.map(({ error, offset, length }) => ({ error, offset, length })),
    }
  }

  // 2. Structural guard.
  const schemaIssue = validateConfigShape(config)
  if (schemaIssue) {
    return { ok: false, code: 'schema_invalid', message: schemaIssue }
  }

  // 3. Identity guard — the file we'd write is computed off the
  //    config's own scope.useCase + scope.tenantId, but the operator
  //    targeted this apply at a specific tenantId. Reject mismatches
  //    so a stray edit doesn't overwrite a different tenant's file.
  if (config.scope.useCase !== USE_CASE) {
    return {
      ok: false,
      code: 'identity_mismatch',
      message: `scope.useCase must be "${USE_CASE}"; got "${config.scope.useCase}"`,
    }
  }
  if (config.scope.tenantId !== input.tenantId) {
    return {
      ok: false,
      code: 'identity_mismatch',
      message: `scope.tenantId must be "${input.tenantId}"; got "${config.scope.tenantId}"`,
    }
  }

  // 4. Dialect/contract resolution + verify.
  if (config.dialectRef.id !== DEFAULT_DIALECT_ID) {
    return {
      ok: false,
      code: 'dialect_unknown',
      message: `only "${DEFAULT_DIALECT_ID}" is supported for litalerts in this MVP; got "${config.dialectRef.id}"`,
    }
  }
  if (config.dialectRef.version !== litalertsV1Dialect.version) {
    return {
      ok: false,
      code: 'dialect_version_mismatch',
      message: `dialectRef.version must be ${litalertsV1Dialect.version}; got ${config.dialectRef.version}`,
    }
  }

  const verifyReport = verifyParser(
    config,
    litalertsV1Dialect,
    litalertsOutputFields,
    litalertsContract.useCase,
  )
  if (!verifyReport.ok) {
    return {
      ok: false,
      code: 'verify_failed',
      message: `${verifyReport.issues.length} safety issue(s)`,
      detail: verifyReport.issues,
    }
  }

  // 5. Compile + run goldens.
  let compiled
  try {
    compiled = compileParser(config, litalertsV1Dialect, litalertsContract)
  } catch (err) {
    return { ok: false, code: 'compile_failed', message: stringifyError(err) }
  }

  for (const rule of config.rules) {
    for (const golden of rule.goldens) {
      const r = parseWith(compiled, golden.input, { snapshotSha: 'apply-validate' })
      if (golden.kind === 'match') {
        if (!r.ok) {
          return {
            ok: false,
            code: 'golden_failed',
            message: `golden "${golden.id}" failed to parse`,
            detail: r,
          }
        }
        if (!deepEqual(r.output, golden.expected)) {
          return {
            ok: false,
            code: 'golden_failed',
            message: `golden "${golden.id}" output mismatch`,
            detail: { expected: golden.expected, actual: r.output },
          }
        }
      } else if (r.ok) {
        return {
          ok: false,
          code: 'golden_failed',
          message: `golden "${golden.id}" expected no_match but parsed`,
          detail: r,
        }
      }
    }
  }

  // 6. Write the file in the local mirror.
  const relPath = `use-cases/${USE_CASE}/parsers/${input.tenantId}.jsonc`
  const absPath = join(repoRoot, relPath)
  try {
    mkdirSync(dirname(absPath), { recursive: true })
    const body = HEADER_COMMENT + JSON.stringify(config, null, 2) + '\n'
    writeFileSync(absPath, body, 'utf8')
  } catch (err) {
    return { ok: false, code: 'git_command_failed', message: `write failed: ${stringifyError(err)}` }
  }

  // 7. git add + commit + push.
  const actor = sanitizeActorEmail(input.actorEmail)
  const commitMessage = buildCommitMessage(input, actor)

  const addResult = runGit(repoRoot, ['add', relPath])
  if (addResult.status !== 0) {
    return { ok: false, code: 'git_command_failed', message: `git add failed: ${addResult.stderr}` }
  }

  // Detect no-op: if nothing was actually changed, skip commit.
  const diffCachedResult = runGit(repoRoot, ['diff', '--cached', '--quiet'])
  if (diffCachedResult.status === 0) {
    return {
      ok: false,
      code: 'git_command_failed',
      message: 'no changes to commit — the proposed JSONC matches the current file byte-for-byte.',
    }
  }

  const commitResult = runGit(repoRoot, [
    '-c',
    `user.email=${actor}`,
    '-c',
    'user.name=helios apply-config',
    'commit',
    '-m',
    commitMessage,
    '--allow-empty-message',
  ])
  if (commitResult.status !== 0) {
    return { ok: false, code: 'git_command_failed', message: `git commit failed: ${commitResult.stderr}` }
  }

  const revParseResult = runGit(repoRoot, ['rev-parse', 'HEAD'])
  const commitSha = revParseResult.stdout.trim()

  const pushResult = runGit(repoRoot, ['push', 'origin', 'HEAD:master'])
  if (pushResult.status !== 0) {
    // Try to recover by resetting HEAD~1 so a retry doesn't accumulate
    // local commits on the mirror.
    runGit(repoRoot, ['reset', '--hard', 'HEAD~1'])
    return {
      ok: false,
      code: 'git_push_failed',
      message: `git push failed: ${pushResult.stderr.trim() || pushResult.stdout.trim()}`,
    }
  }
  const pushed = !/Everything up-to-date/i.test(pushResult.stderr + pushResult.stdout)

  // Kick the registry to refresh sooner than its 60s tick.
  try {
    await getParserRegistry().refresh()
  } catch {
    // Refresh failure is non-fatal — the periodic timer will catch up.
  }

  return { ok: true, relPath, commitSha, pushed }
}

// ---------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------

function validateConfigShape(config: unknown): string | null {
  if (typeof config !== 'object' || config === null) return 'config is not an object'
  const c = config as Record<string, unknown>
  if (c.configVersion !== 1) return `configVersion must be 1 (got ${JSON.stringify(c.configVersion)})`
  if (typeof c.parserId !== 'string' || c.parserId.length === 0) return 'parserId must be a non-empty string'
  if (typeof c.scope !== 'object' || c.scope === null) return 'scope must be an object'
  const scope = c.scope as Record<string, unknown>
  if (typeof scope.tenantId !== 'string' || scope.tenantId.length === 0) return 'scope.tenantId must be a non-empty string'
  if (typeof scope.useCase !== 'string' || scope.useCase.length === 0) return 'scope.useCase must be a non-empty string'
  if (typeof c.dialectRef !== 'object' || c.dialectRef === null) return 'dialectRef must be an object'
  const dref = c.dialectRef as Record<string, unknown>
  if (typeof dref.id !== 'string' || dref.id.length === 0) return 'dialectRef.id must be a non-empty string'
  if (typeof dref.version !== 'number' || !Number.isInteger(dref.version)) return 'dialectRef.version must be an integer'
  if (typeof c.detect !== 'object' || c.detect === null) return 'detect must be an object'
  if (!Array.isArray(c.rules) || c.rules.length === 0) return 'rules must be a non-empty array'
  return null
}

function buildCommitMessage(input: ApplyConfigInput, actor: string): string {
  const note = input.note.trim().slice(0, 400)
  return [
    `litalerts: apply ${input.tenantId} via helios /config/parsing/litalerts`,
    '',
    note || '(no note provided)',
    '',
    `Operator: ${actor}`,
    `Tenant:   ${input.tenantId}`,
    `UseCase:  ${USE_CASE}`,
    `Dialect:  ${DEFAULT_DIALECT_ID} v${litalertsV1Dialect.version}`,
  ].join('\n')
}

function sanitizeActorEmail(email: string): string {
  const trimmed = email.trim()
  // Cheap guardrail: only accept something that vaguely looks like an
  // address. Anything weirder falls back to a service identity.
  if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) return trimmed
  return 'helios-apply-config@freshlybaked.nyc'
}

interface GitResult {
  status: number | null
  stdout: string
  stderr: string
}

function runGit(cwd: string, args: string[]): GitResult {
  const r = spawnSync('git', args, { cwd, encoding: 'utf8', timeout: 30_000 })
  return {
    status: r.status,
    stdout: r.stdout ?? '',
    stderr: r.stderr ?? '',
  }
}

function stringifyError(err: unknown): string {
  if (err instanceof Error) return err.message
  return String(err)
}

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true
  if (typeof a !== typeof b) return false
  if (a === null || b === null) return false
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false
    return a.every((v, i) => deepEqual(v, b[i]))
  }
  if (typeof a === 'object') {
    const ao = a as Record<string, unknown>
    const bo = b as Record<string, unknown>
    const aKeys = Object.keys(ao).sort()
    const bKeys = Object.keys(bo).sort()
    if (aKeys.length !== bKeys.length) return false
    return aKeys.every((k, i) => k === bKeys[i] && deepEqual(ao[k], bo[k]))
  }
  return false
}
