/**
 * export-parsekit-configs — write each in-repo TenantParserConfig
 * literal out as a JSONC file in the layout expected by the
 * `helios-parser-configs` repository.
 *
 * Usage:
 *   tsx helios/scripts/export-parsekit-configs.mts <targetRoot>
 *
 * Produces:
 *   <targetRoot>/use-cases/<useCase>/parsers/<tenantId>.jsonc
 *
 * The output is **plain** JSON (a strict subset of JSONC) prefixed
 * with a `//` provenance comment block. JSONC parsers accept this;
 * strict JSON.parse does not — that's intentional, the loader uses
 * a JSONC parser.
 *
 * This script is read-only against the repo; it does not git-add or
 * commit anything. Drive it from a wrapper if you want that.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { TENANT_CONFIGS } from '../src/lib/parsekit/__tests__/metrc-v1-fixtures.js'
import { LITALERTS_TENANT_CONFIGS } from '../src/lib/parsekit/__tests__/litalerts-v1-fixtures.js'
import type { TenantParserConfig } from '../src/lib/parsekit/index.js'

const SELF_REL =
  'helios/scripts/export-parsekit-configs.mts'

/** Map of useCase id → relative source-of-truth path used in the
 *  AUTOGENERATED provenance header so a future editor can find the
 *  TypeScript literal to mutate. */
const SOURCE_REL_BY_USE_CASE: Record<string, string> = {
  'pending-purchases': 'helios/src/lib/parsekit/__tests__/metrc-v1-fixtures.ts',
  litalerts: 'helios/src/lib/parsekit/__tests__/litalerts-v1-fixtures.ts',
}

function headerComment(cfg: TenantParserConfig): string {
  const sourceRel = SOURCE_REL_BY_USE_CASE[cfg.scope.useCase] ?? '(unknown — see helios/src/lib/parsekit)'
  return [
    '// AUTOGENERATED — do not hand-edit.',
    `// Tenant:    ${cfg.scope.tenantId}`,
    `// Use case:  ${cfg.scope.useCase}`,
    `// Dialect:   ${cfg.dialectRef.id} v${cfg.dialectRef.version}`,
    `// Source:    ${sourceRel}`,
    `// Generated: ${SELF_REL}`,
    '//',
    '// Edit the source-of-truth literal in the helios repo and rerun',
    '// the export script; do not hand-edit this file.',
    '',
  ].join('\n')
}

function writeConfig(targetRoot: string, cfg: TenantParserConfig): string {
  const relDir = join('use-cases', cfg.scope.useCase, 'parsers')
  const absDir = join(targetRoot, relDir)
  mkdirSync(absDir, { recursive: true })
  const absPath = join(absDir, `${cfg.scope.tenantId}.jsonc`)
  const body = JSON.stringify(cfg, null, 2) + '\n'
  writeFileSync(absPath, headerComment(cfg) + body, 'utf8')
  return absPath
}

function main(): void {
  const [, , targetRootArg] = process.argv
  if (!targetRootArg) {
    process.stderr.write(
      `usage: tsx ${SELF_REL} <targetRoot>\n` +
        `  e.g. tsx ${SELF_REL} /home/amp-local/src/helios-parser-configs\n`,
    )
    process.exit(2)
  }
  const targetRoot = resolve(targetRootArg)
  // sanity: don't let a typo turn the repo root into a stray directory
  if (targetRoot === '/' || targetRoot === process.cwd()) {
    process.stderr.write(
      `refusing to write under ${targetRoot}; pick a real target dir.\n`,
    )
    process.exit(2)
  }
  const all: TenantParserConfig[] = [...TENANT_CONFIGS, ...LITALERTS_TENANT_CONFIGS]
  for (const cfg of all) {
    const p = writeConfig(targetRoot, cfg)
    process.stdout.write(`wrote ${p}\n`)
  }
  process.stdout.write(`done — ${all.length} configs.\n`)
}

// Only run when invoked directly (not when imported by tests).
const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invokedDirectly) {
  main()
}
