// FB-US landing-page (LP) family registry — the SINGLE source of truth for
// which FBUS landing-page families exist, their canonical URL shapes, the
// widget `route_patterns` the FAQ widget is scoped onto, and the current
// indexability policy.
//
// This is a VENDORED COPY of the machine-readable artifact that
// `Nicponskis/mostly-static-sites` P0 exports
// (`apps/freshlybakedus-site/lib/seo/lp-family-registry.generated.json`).
// The mss doc (`docs/HOW_FBUS_LP_FAMILY_REGISTRY_WORKS.md`) explicitly
// allows automation P5 to "consume it or pin its SHA"; there is no
// cross-repo build-time fetch in this repo's CI, so we vendor the exact
// artifact verbatim and PIN ITS SOURCE SHA below for provenance / drift
// audit (the same pattern `faqImportFbNyc.ts` uses for the mss FAQ copy).
//
// IMPORTANT — do NOT hand-edit `LP_FAMILY_REGISTRY_ARTIFACT` to add or tweak
// families here. The canonical list lives in mss; this file must only ever
// be REGENERATED by re-copying the upstream artifact and re-pinning the SHA.
// The `faqSourceKey.ts` model is deliberately family-agnostic for the same
// reason: per-family FBUS source keys (`fbus-<family>-faq`) are derived from
// THIS registry's family ids at runtime, never from a second hand-edited list.
//
// child FreshlyBakedNYC/automation#46 · Satisfies: virusdave/top-level#17 ·
// Phase: P5

import { z } from 'zod'

import { fbusFaqSourceKey } from './faqSourceKey.js'

// ── provenance (pin the exact upstream artifact) ──────────────────────

/**
 * Where the vendored artifact was captured from, for audit / re-sync. The
 * upstream artifact ALSO carries its own `provenance.source_commit` (the
 * mss git HEAD at artifact-generation time); both are recorded so a future
 * reader can prove freshness against the mss repo.
 */
export const LP_FAMILY_REGISTRY_PROVENANCE = {
  repo: 'Nicponskis/mostly-static-sites',
  path: 'apps/freshlybakedus-site/lib/seo/lp-family-registry.generated.json',
  /** Default-branch (`master`) commit the artifact was captured at. */
  commitSha: '0e361c2060cc21b817b522a29ba48cf3a9674478',
  /** Git blob sha of the captured artifact file (`git rev-parse HEAD:<path>`). */
  blobSha: 'a63b848e2909fdb86725bfa3330d18a87304ea9c',
  capturedOn: '2026-06-19',
} as const

// ── the vendored artifact (verbatim snake_case JSON) ──────────────────
//
// The byte-for-byte upstream JSON is committed next to this file as
// `lpFamilyRegistry.generated.json` (the audit artifact — its git blob sha
// equals `LP_FAMILY_REGISTRY_PROVENANCE.blobSha`). The const below is the
// RUNTIME mirror of that JSON, kept snake_case so it diffs directly against
// the upstream source; the drift test (`lpFamilyRegistry.test.ts`) binds the
// two (deep-equal + blob-sha) so they can never silently disagree. Both are
// validated by the zod schema below at module load — a malformed copy fails
// LOUD. The const (not the JSON file) is imported so there is no post-build
// asset-copy / runtime JSON-import fragility.

const LP_FAMILY_REGISTRY_ARTIFACT = {
  schema: 'freshlybaked.fbus.lp-family-registry.v1',
  site_id: 'freshlybakedus',
  canonical_host: 'freshlybaked.us',
  provenance: {
    repo: 'Nicponskis/mostly-static-sites',
    source_commit: '1e8018503bc4467a3984b89e765a3e2d8daa8eb8',
    source_commit_semantics:
      'git HEAD at artifact-generation time (parent of the commit that contains this file)',
    generator: 'apps/freshlybakedus-site/scripts/build-lp-family-registry.ts',
  },
  families: [
    {
      id: 'deliverance',
      aliases: [],
      slug_kind: 'site-slug',
      max_variant: 5,
      canonical_representative_route: '/midtown/deliverance/midtown/1',
      widget_route_patterns: ['/midtown/deliverance/midtown/*', '/bronx/deliverance/bronx/*'],
      route_patterns: [
        {
          kind: 'canonical_content',
          path_template: '/{location}/deliverance/{location}/{variant}',
          widget_patterns: ['/midtown/deliverance/midtown/*', '/bronx/deliverance/bronx/*'],
          regex_source: '^/(midtown|bronx)/deliverance/\\1/[1-5]/?$',
        },
        {
          kind: 'random_rotation_alias',
          path_template: '/{location}/deliverance/{location}/0',
          regex_source: '^/(midtown|bronx)/deliverance/\\1/0/?$',
        },
      ],
      indexability_policy: { kind: 'all_variants', robots: 'noindex,nofollow' },
      sample_crawl_routes: [
        { path: '/midtown/deliverance/midtown/1', kind: 'canonical-content', slug_source: 'static' },
        { path: '/bronx/deliverance/bronx/1', kind: 'canonical-content', slug_source: 'static' },
        {
          path: '/midtown/deliverance/midtown/0',
          kind: 'random-rotation-alias',
          slug_source: 'static',
        },
      ],
      provenance: {
        source_paths: [
          'apps/freshlybakedus-site/lib/purpose-families.ts',
          'apps/freshlybakedus-site/app/freshlybakedus-deliverance-data.ts',
        ],
      },
    },
    {
      id: 'recurse',
      aliases: [],
      slug_kind: 'site-slug',
      max_variant: 5,
      canonical_representative_route: '/midtown/recurse/midtown/1',
      widget_route_patterns: ['/midtown/recurse/midtown/*', '/bronx/recurse/bronx/*'],
      route_patterns: [
        {
          kind: 'canonical_content',
          path_template: '/{location}/recurse/{location}/{variant}',
          widget_patterns: ['/midtown/recurse/midtown/*', '/bronx/recurse/bronx/*'],
          regex_source: '^/(midtown|bronx)/recurse/\\1/[1-5]/?$',
        },
        {
          kind: 'random_rotation_alias',
          path_template: '/{location}/recurse/{location}/0',
          regex_source: '^/(midtown|bronx)/recurse/\\1/0/?$',
        },
      ],
      indexability_policy: { kind: 'all_variants', robots: 'noindex,nofollow' },
      sample_crawl_routes: [
        { path: '/midtown/recurse/midtown/1', kind: 'canonical-content', slug_source: 'static' },
        { path: '/bronx/recurse/bronx/1', kind: 'canonical-content', slug_source: 'static' },
        {
          path: '/midtown/recurse/midtown/0',
          kind: 'random-rotation-alias',
          slug_source: 'static',
        },
      ],
      provenance: {
        source_paths: [
          'apps/freshlybakedus-site/lib/purpose-families.ts',
          'apps/freshlybakedus-site/app/freshlybakedus-recurse-data.ts',
        ],
      },
    },
    {
      id: 'tours',
      aliases: [],
      slug_kind: 'site-slug',
      max_variant: 5,
      canonical_representative_route: '/midtown/tours/midtown/1',
      widget_route_patterns: ['/midtown/tours/midtown/*', '/bronx/tours/bronx/*'],
      route_patterns: [
        {
          kind: 'canonical_content',
          path_template: '/{location}/tours/{location}/{variant}',
          widget_patterns: ['/midtown/tours/midtown/*', '/bronx/tours/bronx/*'],
          regex_source: '^/(midtown|bronx)/tours/\\1/[1-5]/?$',
        },
        {
          kind: 'random_rotation_alias',
          path_template: '/{location}/tours/{location}/0',
          regex_source: '^/(midtown|bronx)/tours/\\1/0/?$',
        },
      ],
      indexability_policy: {
        kind: 'variant_overrides',
        default_robots: 'noindex,nofollow',
        variant_robots: { '1': 'index,follow' },
      },
      sample_crawl_routes: [
        { path: '/midtown/tours/midtown/1', kind: 'canonical-content', slug_source: 'static' },
        { path: '/bronx/tours/bronx/1', kind: 'canonical-content', slug_source: 'static' },
        { path: '/midtown/tours/midtown/0', kind: 'random-rotation-alias', slug_source: 'static' },
      ],
      provenance: {
        source_paths: [
          'apps/freshlybakedus-site/lib/purpose-families.ts',
          'apps/freshlybakedus-site/app/freshlybakedus-tour-variant-data.ts',
        ],
      },
    },
    {
      id: 'branding',
      aliases: [],
      slug_kind: 'per-row-slug',
      max_variant: 5,
      canonical_representative_route: '/midtown/branding/camino/1',
      widget_route_patterns: ['/midtown/branding/*', '/bronx/branding/*'],
      route_patterns: [
        {
          kind: 'canonical_content',
          path_template: '/{location}/branding/{brandSlug}/{variant}',
          widget_patterns: ['/midtown/branding/*', '/bronx/branding/*'],
          regex_source: '^/(midtown|bronx)/branding/[^/]+/[1-5]/?$',
        },
        {
          kind: 'random_rotation_alias',
          path_template: '/{location}/branding/{brandSlug}/0',
          regex_source: '^/(midtown|bronx)/branding/[^/]+/0/?$',
        },
      ],
      indexability_policy: { kind: 'all_variants', robots: 'noindex,nofollow' },
      sample_crawl_routes: [
        {
          path: '/midtown/branding/camino/1',
          kind: 'canonical-content',
          slug_source: 'curated-dynamic-slug',
        },
      ],
      provenance: {
        source_paths: [
          'apps/freshlybakedus-site/lib/purpose-families.ts',
          'apps/freshlybakedus-site/app/freshlybakedus-brand-variant-data.ts',
        ],
      },
    },
    {
      id: 'compare',
      aliases: ['conquest'],
      internal_data_family: 'conquest',
      slug_kind: 'per-row-slug',
      max_variant: 5,
      canonical_representative_route: '/midtown/compare/NUYBA6PPFTTU/1',
      widget_route_patterns: [
        '/midtown/compare/*',
        '/bronx/compare/*',
        '/compare/midtown/*',
        '/compare/bronx/*',
      ],
      route_patterns: [
        {
          kind: 'canonical_content',
          path_template: '/{location}/compare/{competitorPublicId}/{variant}',
          widget_patterns: ['/midtown/compare/*', '/bronx/compare/*'],
          regex_source: '^/(midtown|bronx)/compare/[^/]+/[1-5]/?$',
        },
        {
          kind: 'random_rotation_alias',
          path_template: '/{location}/compare/{competitorPublicId}/0',
          regex_source: '^/(midtown|bronx)/compare/[^/]+/0/?$',
        },
        {
          kind: 'legacy_redirect',
          path_template: '/compare/{location}/{competitorPublicId}/{variant}',
          widget_patterns: ['/compare/midtown/*', '/compare/bronx/*'],
          regex_source: '^/compare/(midtown|bronx)/[^/]+/\\d+/?$',
        },
      ],
      indexability_policy: { kind: 'all_variants', robots: 'noindex,nofollow' },
      sample_crawl_routes: [
        {
          path: '/midtown/compare/NUYBA6PPFTTU/1',
          kind: 'canonical-content',
          slug_source: 'committed-dataset',
        },
        {
          path: '/bronx/compare/FDGA2DB72DVJ/1',
          kind: 'canonical-content',
          slug_source: 'committed-dataset',
        },
      ],
      provenance: {
        source_paths: [
          'apps/freshlybakedus-site/lib/purpose-families.ts',
          'apps/freshlybakedus-site/conquest-data/competitor-production-url-map.json',
        ],
      },
    },
  ],
} as const

// ── zod schema (validate the vendored copy at load; fail loud) ────────

export const LP_FAMILY_REGISTRY_SCHEMA_ID = 'freshlybaked.fbus.lp-family-registry.v1'

const IndexabilityPolicySchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('all_variants'), robots: z.string().min(1) }),
  z.object({
    kind: z.literal('variant_overrides'),
    default_robots: z.string().min(1),
    variant_robots: z.record(z.string(), z.string().min(1)),
  }),
])

const RoutePatternSchema = z.object({
  kind: z.string().min(1),
  path_template: z.string().min(1),
  widget_patterns: z.array(z.string().min(1)).optional(),
  regex_source: z.string().min(1),
})

const SampleCrawlRouteSchema = z.object({
  path: z.string().min(1),
  kind: z.string().min(1),
  slug_source: z.string().min(1),
})

const LpFamilySchema = z.object({
  id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  aliases: z.array(z.string().min(1)),
  internal_data_family: z.string().min(1).optional(),
  slug_kind: z.string().min(1),
  max_variant: z.number().int().positive(),
  canonical_representative_route: z.string().min(1),
  widget_route_patterns: z.array(z.string().min(1)).min(1),
  route_patterns: z.array(RoutePatternSchema).min(1),
  indexability_policy: IndexabilityPolicySchema,
  sample_crawl_routes: z.array(SampleCrawlRouteSchema).min(1),
  provenance: z.object({ source_paths: z.array(z.string().min(1)) }),
})

const LpFamilyRegistrySchema = z.object({
  schema: z.literal(LP_FAMILY_REGISTRY_SCHEMA_ID),
  site_id: z.string().min(1),
  canonical_host: z.string().min(1),
  provenance: z.object({
    repo: z.string().min(1),
    source_commit: z.string().min(1),
    source_commit_semantics: z.string().min(1),
    generator: z.string().min(1),
  }),
  families: z.array(LpFamilySchema).min(1),
})

export type LpFamily = z.infer<typeof LpFamilySchema>
export type LpFamilyRegistry = z.infer<typeof LpFamilyRegistrySchema>

// Validate the vendored copy ONCE at module load. A malformed/typo'd copy
// (e.g. a botched re-sync) throws here rather than silently shipping junk.
const REGISTRY: LpFamilyRegistry = LpFamilyRegistrySchema.parse(LP_FAMILY_REGISTRY_ARTIFACT)

const FAMILY_BY_KEY: ReadonlyMap<string, LpFamily> = (() => {
  const map = new Map<string, LpFamily>()
  const register = (key: string, family: LpFamily): void => {
    const existing = map.get(key)
    if (existing && existing.id !== family.id) {
      // A future upstream id/alias collision must fail LOUD, not silently
      // shadow an earlier family.
      throw new Error(
        `LP-family registry key collision on ${JSON.stringify(key)} ` +
          `(families ${existing.id} and ${family.id}).`,
      )
    }
    map.set(key, family)
  }
  for (const family of REGISTRY.families) {
    register(family.id, family)
    for (const alias of family.aliases) {
      register(alias, family)
    }
  }
  return map
})()

// ── accessors ─────────────────────────────────────────────────────────

/** The validated, vendored LP-family registry. */
export function getLpFamilyRegistry(): LpFamilyRegistry {
  return REGISTRY
}

/** All families, in registry order. */
export function listLpFamilies(): readonly LpFamily[] {
  return REGISTRY.families
}

/** Every recognized family id (canonical ids only, no aliases). */
export function lpFamilyIds(): readonly string[] {
  return REGISTRY.families.map((f) => f.id)
}

/**
 * Resolve a canonical id OR a known alias (e.g. `conquest` → `compare`) to
 * the registry family, or `null` if unrecognized.
 */
export function getLpFamily(idOrAlias: string): LpFamily | null {
  return FAMILY_BY_KEY.get(idOrAlias) ?? null
}

/**
 * Normalize a canonical id or alias to the canonical family id (e.g.
 * `conquest` → `compare`), or `null` if unrecognized.
 */
export function resolveLpFamilyId(idOrAlias: string): string | null {
  return FAMILY_BY_KEY.get(idOrAlias)?.id ?? null
}

/**
 * The canonical FBUS FAQ source key for a family (`fbus-<id>-faq`). Accepts
 * an id or alias; throws if unrecognized so a junk family can never mint a
 * draft under a bogus key.
 */
export function lpFamilyFaqSourceKey(idOrAlias: string): string {
  const family = getLpFamily(idOrAlias)
  if (!family) {
    throw new Error(
      `Unknown LP family ${JSON.stringify(idOrAlias)} ` +
        `(known: ${lpFamilyIds().join(', ')}).`,
    )
  }
  return fbusFaqSourceKey(family.id)
}
