#!/usr/bin/env python3
"""Generate the static task-dag shell symbol inventory (issue #76, Wave 0).

This intentionally uses a conservative lexer rather than pretending to parse
all of Bash. It is deterministic, dependency-free, and records enough raw
facts to make provider changes and cross-file coupling reviewable.
"""

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
FILES = [ROOT / "scripts/task-dag", *sorted((ROOT / "scripts/task-dag.d").glob("*.sh"))]
FUNC = re.compile(
    r'^(?P<indent>\s*)(?:function\s+(?P<function>[A-Za-z_][A-Za-z0-9_]*)'
    r'(?:\s*\(\s*\))?|(?P<posix>[A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\))\s*\{'
)
VAR = re.compile(r'\$\{?([A-Za-z_][A-Za-z0-9_]*)')
CALL = re.compile(r'(?<![$\w])([A-Za-z_][A-Za-z0-9_]*)(?=\s|$|[;&|()])')
ASSIGN = re.compile(r'^\s*(?:export\s+|readonly\s+)?([A-Za-z_][A-Za-z0-9_]*)=')
KEYWORDS = {
    'case', 'do', 'done', 'elif', 'else', 'esac', 'false', 'fi', 'for',
    'function', 'if', 'in', 'local', 'return', 'then', 'true', 'until', 'while',
}

def rel(path):
    return path.relative_to(ROOT).as_posix()

def generate():
    providers, refs, calls, assignments = {}, [], [], []
    for path in FILES:
        # Functions in this codebase close with a brace at the definition's
        # indentation. Keeping an indentation-aware stack handles its nested
        # helper functions without counting AWK's `BEGIN {` or shell command
        # groups (`if { ...; }`) as providers.
        functions = []
        for no, line in enumerate(path.read_text().splitlines(), 1):
            if functions and re.match(r'^' + re.escape(functions[-1][0]) + r'}(?:\s|$)', line):
                functions.pop()
            m = FUNC.match(line)
            if m:
                name = m.group('function') or m.group('posix')
                functions.append((m.group('indent'), name))
                providers.setdefault(name, []).append((rel(path), no))
            current = functions[-1][1] if functions else '<top-level>'
            # Remove comments only; quoted # is a documented approximation.
            code = line.split('#', 1)[0]
            for name in VAR.findall(code): refs.append((name, rel(path), current, no))
            m = ASSIGN.match(code)
            if m and current == '<top-level>': assignments.append((m.group(1), rel(path), no))
            if not FUNC.match(code):
                for name in CALL.findall(code):
                    if name not in KEYWORDS:
                        calls.append((name, rel(path), current, no))
    out = ['# task-dag static provider/consumer inventory', '',
           '<!-- Generated by scripts/task-dag-inventory.py; do not edit. -->',
           '', 'Scope: `scripts/task-dag` and every `scripts/task-dag.d/*.sh` (sorted bytewise).',
           'Calls through variables, `eval`, aliases, generated shell, command strings, and runtime',
           'dispatch cannot be resolved statically. Comment/quote handling is deliberately conservative;',
           'entries are review leads, not a proof of runtime reachability. `function@line` uses',
           'indentation-aware lexical containment, not a full Bash parse. Duplicate providers are retained because they',
           'expose source-order overrides and the current early-load + glob/double-load cycles.', '']
    out += ['## Function providers', '', '| symbol | providers (source order within file set) |', '|---|---|']
    for name in sorted(providers):
        out.append(f"| `{name}` | " + '<br>'.join(f'`{p}:{n}`' for p,n in providers[name]) + ' |')
    out += ['', '## Known function consumers', '', '| symbol | consumers |', '|---|---|']
    for name in sorted(providers):
        seen=[]
        for called,p,fn,n in calls:
            if called == name and (p,fn,n) not in seen: seen.append((p,fn,n))
        if seen: out.append(f"| `{name}` | " + '<br>'.join(f'`{p}:{n} ({fn})`' for p,fn,n in seen) + ' |')
    globals_known = {x[0] for x in assignments}
    out += ['', '## Top-level globals and consumers', '', '| global | providers | consumers |', '|---|---|---|']
    for name in sorted(globals_known):
        ps='<br>'.join(f'`{p}:{n}`' for x,p,n in assignments if x==name)
        cs=[]
        for x,p,fn,n in refs:
            if x==name and fn!='<top-level>' and (p,fn,n) not in cs: cs.append((p,fn,n))
        out.append(f"| `{name}` | {ps} | " + ('<br>'.join(f'`{p}:{n} ({fn})`' for p,fn,n in cs) or '—') + ' |')
    out += ['', '## Loader source statements', '', '| location | text |', '|---|---|']
    for path in FILES:
        for no,line in enumerate(path.read_text().splitlines(),1):
            if re.match(r'^\s*(?:source|\.)\s+["$/(]', line) or ('for __ext in' in line):
                out.append(f'| `{rel(path)}:{no}` | `{line.strip().replace("|", "\\|")}` |')
    return '\n'.join(out)+'\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'docs/task-dag-function-inventory.md'
    content = generate()
    if args.check:
        if not target.exists() or target.read_text() != content:
            print(
                f'{target.relative_to(ROOT)} is stale; run scripts/task-dag-inventory.py',
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        target.write_text(content)
